# Generated by Django 5.2.9 on 2025-12-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capability',
            old_name='code',
            new_name='name',
        ),
    ]
