# Generated by Django 5.2.9 on 2025-12-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_activitylog_extra_activitylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
    ]
